#!/usr/bin/env python3
"""Generate assets/manifest.json from what is actually on disk.

Generated rather than hand-maintained on purpose: a manifest that is
edited by hand becomes a description of what someone intended, and the
point of this file is to be able to trust it. Every entry is checked
against the filesystem and against the .tres that references it, so
"integrated" means integrated.
"""

import json
import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(TOOLS, ".."))
sys.path.insert(0, TOOLS)

import asset_specs  # noqa: E402
from build_icons import ICONS  # noqa: E402
from wire_visuals import MAPPING  # noqa: E402

STYLE_BLOCK = (
    "Near-future military RTS asset, stylized realistic low-poly, dark serious "
    "atmosphere, modern military (NOT sci-fi). Desaturated palette: gunmetal "
    "#3A3F45, steel #4A5058, olive drab #4A5138, concrete #8A8579, rust #6E4A2E. "
    "Flat matte painted metal. Boxy chamfered industrial shape language with an "
    "exaggerated readable silhouette. Single cold low dusk sun. Top-down "
    "isometric RTS camera ~38m out, optimized for Android."
)

VFX_EFFECTS = [
    ("vfx_muzzle_flash", "Small-arms muzzle flash"),
    ("vfx_cannon_flash", "Tank cannon flash with smoke"),
    ("vfx_artillery_flash", "Artillery muzzle blast"),
    ("vfx_tracer", "Bullet tracer streak"),
    ("vfx_impact", "Small-arms impact sparks and dust"),
    ("vfx_shell_impact", "High-explosive shell impact"),
    ("vfx_explosion_small", "Small explosion"),
    ("vfx_explosion_large", "Large structure explosion"),
    ("vfx_vehicle_wreck", "Destroyed vehicle fire and smoke column"),
    ("vfx_damage_smoke", "Damaged structure smoke plume"),
    ("vfx_damage_fire", "Heavily damaged structure fire"),
    ("vfx_construction_dust", "Construction dust burst"),
    ("vfx_capture_effect", "Structure capture burst"),
    ("vfx_selection_marker", "Selection ring"),
    ("vfx_command_marker", "Move/attack command marker"),
]


def triangles_of(spec):
    from glb import Mesh  # noqa: F401
    nodes = spec["builder"]()
    return sum(len(g[2]) // 3 for _, mesh, _ in nodes for g in mesh.groups.values())


def referenced_by(model_id):
    return sorted(path for path, mapped in MAPPING.items() if mapped == model_id)


def main():
    entries = []
    missing = []

    for asset_id, spec in sorted(asset_specs.ASSETS.items()):
        rel = "assets/models/%s.glb" % asset_id
        exists = os.path.isfile(os.path.join(ROOT, rel))
        if not exists:
            missing.append(rel)
        users = referenced_by(asset_id)
        overhang = asset_specs.OVERHANG.get(asset_id, (0.0, 0.0, 0.0))
        entries.append({
            "id": asset_id,
            "type": "model_%s" % spec["class"],
            "filename": rel,
            "dimensions_m": {
                "width": spec["size"][0], "height": spec["size"][1],
                "depth": spec["size"][2],
            },
            "declared_overhang_m": {
                "x": overhang[0], "y": overhang[1], "z": overhang[2],
            } if any(overhang) else None,
            "triangles": triangles_of(spec),
            "triangle_budget": spec["tri_budget"],
            "description": spec["description"],
            "status": "greybox",
            "source": "generated by tools/build_greyboxes.py from tools/asset_specs.py",
            "prompt": None,
            "integration": ("referenced by " + ", ".join(users)) if users
                           else "spawned by scripts/core/scenery.gd",
            "integrated": bool(users) or spec["class"] == "environment",
        })

    for icon_id in sorted(ICONS):
        rel = "assets/icons/%s.svg" % icon_id
        if not os.path.isfile(os.path.join(ROOT, rel)):
            missing.append(rel)
        entries.append({
            "id": icon_id,
            "type": "icon",
            "filename": rel,
            "dimensions_m": None,
            "triangles": None,
            "description": "UI icon, 64x64 vector",
            "status": "placeholder-final",
            "source": "generated by tools/build_icons.py",
            "prompt": None,
            "integration": "scripts/ui/icons.gd -> HUD build list, tabs and order buttons",
            "integrated": True,
        })

    for effect_id, description in VFX_EFFECTS:
        entries.append({
            "id": effect_id,
            "type": "vfx",
            "filename": "scripts/vfx/vfx.gd",
            "dimensions_m": None,
            "triangles": None,
            "description": description,
            "status": "final-placeholder",
            "source": "procedural CPUParticles3D, scripts/vfx/vfx.gd",
            "prompt": None,
            "integration": "weapon.gd, unit_base.gd, building_base.gd",
            "integrated": True,
        })

    # Art produced by Codex in an earlier pass, kept and catalogued rather
    # than regenerated - the project's rule is to inspect before replacing.
    codex_dir = os.path.join(ROOT, "assets", "generated_rts")
    if os.path.isdir(codex_dir):
        for name in sorted(os.listdir(codex_dir)):
            if not name.endswith(".png"):
                continue
            entries.append({
                "id": "codex_" + name[:-4],
                "type": "texture_concept",
                "filename": "assets/generated_rts/%s" % name,
                "dimensions_m": None,
                "triangles": None,
                "description": "Codex-generated concept art from the earlier asset pass",
                "status": "generated",
                "source": "Codex image generation",
                "prompt": STYLE_BLOCK,
                "integration": "reference only; not referenced by any scene",
                "integrated": False,
            })

    by_status = {}
    for entry in entries:
        by_status[entry["status"]] = by_status.get(entry["status"], 0) + 1

    manifest = {
        "project": "Operation Midnight",
        "art_direction": "docs/ART_DIRECTION.md",
        "style_block": STYLE_BLOCK,
        "generated_by": "tools/build_manifest.py",
        "totals": {
            "assets": len(entries),
            "by_type": {},
            "by_status": by_status,
            "integrated": sum(1 for e in entries if e["integrated"]),
            "model_triangles": sum(e["triangles"] or 0 for e in entries),
        },
        "assets": entries,
    }
    for entry in entries:
        key = entry["type"]
        manifest["totals"]["by_type"][key] = manifest["totals"]["by_type"].get(key, 0) + 1

    path = os.path.join(ROOT, "assets", "manifest.json")
    with open(path, "w") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")

    print("manifest: %d assets, %d integrated, %d model triangles" % (
        len(entries), manifest["totals"]["integrated"],
        manifest["totals"]["model_triangles"]))
    for key in sorted(manifest["totals"]["by_type"]):
        print("  %-18s %d" % (key, manifest["totals"]["by_type"][key]))
    if missing:
        print("\nMISSING %d file(s):" % len(missing))
        for rel in missing:
            print("  " + rel)
        return 1
    print("\nEvery referenced file exists.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
